run:
  concurrency: 4
  timeout: 5m

  skip-dirs:
    - plugins/parsers/influx

linters:
  enable:
    - asciicheck
    - nolintlint
    - errorlint
    # - ifshort # doesn't really work... (x := someFunc(); if x ... then x used later, linter complains var isn't used)
  fast: true