run:
  timeout: 5m
  skip-dirs:
    - plugins/parsers/influx
  skip-files:
    - "plugins/parsers/influx/*"

linters:
  fast: false
  disable-all: false
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    # - revive
    - gosec
    - misspell
    - unparam
    - prealloc
    - exportloopref
    - gocritic
    - asciicheck
    - errorlint
    - unconvert
  disable:
    ## deprecated linters
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    # - nosnakecase
    - scopelint
    - structcheck
    - varcheck
