run:
  concurrency: 4
  timeout: 5m

  skip-files:
    - plugins/parsers/influx/*

linters:
  fast: true
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    # - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - golint
    - gosec
    - interfacer
    - misspell
    - unparam
    - prealloc
    - scopelint
    - gocritic
    - asciicheck
    - errorlint
    - unconvert
    - wrapcheck
    # - goconst
    # - nolintlint # different linters with different GOOS fire issues GOOS=linux 'structcheck' unused, under GOOS=darwin it's required
    # - ifshort # doesn't really work... (x := someFunc(); if x ... then x used later, linter complains var isn't used)
